# -*- coding: utf-8 -*-
"""121-130_exercises_solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RjpoGoQfyzlAeHvFzI81bfEi7UG0m3SS

## Pandas

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 121](#1)
* [Exercise 122](#2)
* [Exercise 123](#3)
* [Exercise 124](#4)
* [Exercise 125](#5)
* [Exercise 126](#6)
* [Exercise 127](#7)
* [Exercise 128](#8)
* [Exercise 129](#9)
* [Exercise 130](#10)

### <a name='0'></a> Import of libraries
"""

import numpy as np
import pandas as pd
import seaborn as sns

sns.set()
np.__version__

"""The _fetch_financial_data()_ function fetches data on listed companies. It will be used in the following exercises. To download data of a specific company, you must provide the ticker (symbol) of the company.
Функцията _fetch_financial_data()_ извлича данни за регистрирани компании. Ще се използва в следващите упражнения. За да изтеглите данни за конкретна компания, трябва да предоставите тикера (символ) на компанията.

Some sample company tickers:
Някои примерни фирмени тикери:
* AMZN - Amazon
* GOOGL - Google
* MSFT - Microsoft
* AAPL - Apple
* NKE - Nike
* WMT - Walmart
"""

def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations.
Тази функция извлича борсови котировки.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

"""### <a name='1'></a> Exercise 121
Using the _fetch_financial_data()_ function, download Google (Alphabet) quotes and assign to the variable _google_. Display object _google_.
Използвайки функцията _fetch_financial_data()_, изтеглете котировките на Google (Азбука) и ги присвоете на променливата _google_. Показване на обект _google_.
"""

google = fetch_financial_data('GOOGL')
google

"""### <a name='2'></a> Exercise 122
Display basic information about _google_ object.
Показване на основна информация за _google_ обект.
"""

google.info()

"""Display basic statistics for _google_."""
"""Показване на основни статистики за _google_."""

google.describe()

"""Note the precision of individual statistics.
Try setting the appropriate _pandas_ library options to display data with two decimal places.
Обърнете внимание на точността на отделните статистики.
Опитайте да зададете подходящите опции на библиотеката _pandas_ за показване на данни с два знака след десетичната запетая.

__Tip:__
https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html
"""

pd.set_option('precision', 2)
google.describe()

"""__Additionally:__
The following setting will also suppress mathematical notation (see column _Volume_).
Следната настройка също така ще потисне математическата нотация (вижте колона _Volume_).
"""

pd.options.display.float_format = '{:.2f}'.format
google.describe()

"""Build a simple chart for _google_ closing price (_Close_)"""
""Изградете проста диаграма за _google_ цената на затваряне (_Close_)"""

google['Close'].plot()

"""### <a name='3'></a> Exercise 123
Replace the _Date_ index with a column. Permanently assign changes to the _google_.
Заменете индекса _Date_ с колона. Постоянно присвояване на промените на _google_.
"""

google = google.reset_index()
google

"""Assign two new columns to the _google_ object by adding a column with the current month number named _'Month'_ and the year named _'Year'_."""
"""Присвоете две нови колони към обекта _google_, като добавите колона с номера на текущия месец с име _'Month'_ и годината с име _'Year'_."""

google['Year'] = google['Date'].dt.year
google['Month'] = google['Date'].dt.month
google

"""### <a name='4'></a> Exercise 124
Compute the average closing price (_Close_) for a particular year (group data by year - column _Year_ and then calculate the average value).
Изчислете средната цена на затваряне (_Close_) за определена година (групирайте данните по година - колона _Year_ и след това изчислете средната стойност).
"""

google.groupby('Year')['Close'].mean()

"""Present the obtained values on the graph using the _plot()_ method."""
"""Представете получените стойности на графиката с помощта на метода _plot()_."""

google.groupby('Year')['Close'].mean().plot()

"""Compute the average closing price (_Close_) for the month (group data by month - the _Month_ column and then count the average value)."""
"""Изчислете средната цена на затваряне (_Close_) за месеца (групирайте данните по месец - колоната _Month_ и след това пребройте средната стойност)."""

google.groupby('Month')['Close'].mean()

"""Present the obtained values on the graph using the _plot()_ method.
Note which months may indicate weaker periods on the stock market.
Представете получените стойности на графиката с помощта на метода _plot()_.
Обърнете внимание кои месеци може да показват по-слаби периоди на фондовия пазар.
"""

google.groupby('Month')['Close'].mean().plot()

"""### <a name='5'></a> Exercise 125
Group data from _google_ at year and month level. Then calculate the average value.
Групирайте данните от _google_ на ниво година и месец. След това изчислете средната стойност.

"""

google.groupby(['Year', 'Month'])['Close'].mean()

"""### <a name='6'></a> Exercise 126
Find the index for which the _Close_ column has the largest value.
Намерете индекса, за който колоната _Close_ има най-голямата стойност.

"""

google['Close'].argmax()

"""Extract the row for this index from the google object as a DataFrame. Read the date."""
"""Извлечете реда за този индекс от обекта на google като DataFrame. Прочетете датата."""

google.iloc[[google['Close'].argmax()]]

"""### <a name='7'></a> Exercise 127
Extract the columns _Date_, _Open_, _Close_, _Volume_ from the _google_ object.
Don't change the original _google_ object!
Извлечете колоните _Date_, _Open_, _Close_, _Volume_ от обекта _google_.
Не променяйте оригиналния _google_ обект!
"""

google[['Date', 'Open', 'Close', 'Volume']]

"""### <a name='8'></a> Exercise 128
Set the index for the _Date_ column back. Display object _google_.
Задайте обратно индекса за колоната _Date_. Показване на обект _google_.
"""

google = google.set_index('Date')
google

"""### <a name='9'></a> Exercise 129
Permanently remove the _Year_ and _Month_ columns from the _google_ object. Display object _google_.
Премахнете завинаги колоните _Year_ и _Month_ от обекта _google_. Показване на обект _google_.
"""

google = google.drop(columns=['Year', 'Month'])
google

"""### <a name='10'></a> Exercise 130

Assign the following values to the column names:
Присвоете следните стойности на имената на колоните:
* Open -> O
* High -> H
* Low -> L
* Close -> C
* Volume -> V

to object _google_. Display object _google_.
"""

google.columns = ['O', 'H', 'L', 'C', 'V']
google

